"""initial schema

Revision ID: aa65b69e08bd
Revises: 
Create Date: 2026-08-28 22:34:03.280948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa65b69e08bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('processed_chunks', sa.Integer(), nullable=False),
    sa.Column('current_chunk', sa.Integer(), nullable=True),
    sa.Column('okf_concept_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_staging',
    sa.Column('doc_id', sa.String(length=16), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('processed_chunks', sa.JSON(), nullable=True),
    sa.Column('used_slugs', sa.JSON(), nullable=True),
    sa.Column('global_tags', sa.JSON(), nullable=True),
    sa.Column('chunks_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('document_tags',
    sa.Column('doc_id', sa.String(length=16), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id', 'tag')
    )
    op.create_table('okf_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('saved_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_okf_attachments_doc_id'), 'okf_attachments', ['doc_id'], unique=False)
    op.create_table('okf_concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('relations', sa.JSON(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'slug', name='uq_okf_concepts_doc_slug')
    )
    op.create_index(op.f('ix_okf_concepts_doc_id'), 'okf_concepts', ['doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_okf_concepts_doc_id'), table_name='okf_concepts')
    op.drop_table('okf_concepts')
    op.drop_index(op.f('ix_okf_attachments_doc_id'), table_name='okf_attachments')
    op.drop_table('okf_attachments')
    op.drop_table('document_tags')
    op.drop_table('document_staging')
    op.drop_table('user_roles')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
